services:
  bun-blog:
    image: bun-blog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./posts
        target: /usr/app/posts
      - type: bind
        source: ./static
        target: /usr/app/static
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:3000/
    user: bun
