services:
  bun-blog:
    image: bun-blog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./posts
        target: /usr/app/posts
      - type: bind
        source: ./static
        target: /usr/app/static
      - blog:/usr/app/static/json
    entrypoint: ["bun", "run", "--watch", "index.ts"]
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:3000/
    networks:
      - frontend
    user: bun
  bun-blog-mobile:
    image: bun-blog-mobile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3111:3000"
    volumes:
      - type: bind
        source: ./posts
        target: /usr/app/posts
      - type: bind
        source: ./static
        target: /usr/app/static
      - blog:/usr/app/static/json
    entrypoint: ["bun", "run", "--watch", "index.ts"]
    environment:
      - NODE_ENV=development
      - API_URL=http://10.0.2.2:3111/
    networks:
      - frontend
    user: bun
  webring:
    image: webring
    build:
      context: ./scripts/
      dockerfile: Dockerfile
    depends_on:
      - bun-blog
    networks:
    - backend
    volumes:
      - blog:/usr/app/static/json
volumes:
  blog:
networks:
  frontend:
  backend:
